version: "3.4"  # this must match the version in docker-compose.yml
services:
    proxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxymanager
    labels:
      - "com.dockstarter.appinfo.description: NGINX Proxy Manager"
      - "com.dockstarter.appinfo.nicename: NGINX Proxy Manager"
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      - FORCE_COLOR=1
      - NODE_ENV=config
    volumes:
      - /opt/appdata/proxymanager/config.json:/app/config/config.json
      - /opt/appdata/proxymanager/data:/data
      - /opt/appdata/proxymanager/letsencrypt:/etc/letsencrypt
      - ${DOCKERSHAREDDIR}:/shared
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    labels:
      - "com.dockstarter.appinfo.description: MariaDB for NGINX Proxy Manager"
      - "com.dockstarter.appinfo.nicename: DB NGINX Proxy Manager"
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD:ChangeMe"
      - "MYSQL_DATABASE:proxymgr"
      - "MYSQL_USER:ChangeMe"
      - "MYSQL_PASSWORD:ChangeMe"
      - "FORCE_COLOR:1"
    volumes:
      - /opt/appdata/mariadb:/var/lib/mysql
      - ${DOCKERSHAREDDIR}:/shared
    restart: unless-stopped
